nombreCompleto = input("¿Cuál es su nombre completo? ")
n = input("Introduce un número entero: ")
print((nombreCompleto.lower() + "\n") * int(n))
print((nombreCompleto.upper() + "\n") * int(n))
print((nombreCompleto.title() + "\n") * int(n))